routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $data['title'] = "Login ";
    return view('auth.login', $data);
})->middleware('guest');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('car', 'CarController')->middleware('auth');

Route::resource('brand', 'BrandController')->middleware('auth');

Route::resource('employee', 'EmployeeController')->middleware('auth');

Route::resource('client', 'ClientController')->middleware('auth');

Route::get('booking', ['as' => 'booking.index', 'uses' => 'BookingController@index' ])->middleware('auth');

Route::get('list-member', 'BookingController@listMember' )->middleware('auth');

Route::post('create-client', ['as' => 'create-client', 'uses' => 'BookingController@createClient' ])->middleware('auth');

Route::post('booking/details', ['as' => 'booking.calculate', 'uses' => 'BookingController@calculate'])->middleware('auth');

Route::post('booking/process', ['as' => 'booking.process', 'uses' => 'BookingController@process'])->middleware('auth');

Route::get('returns', ['as' => 'returns.index', 'uses' => 'ReturnController@index' ])->middleware('auth');

Route::get('returns/information', ['as' => 'returns.information', 'uses' => 'ReturnController@information'])->middleware('auth');

Route::post('returns/process', ['as' => 'returns.process', 'uses' => 'ReturnController@process'])->middleware('auth');

Route::get('reports/transaction', 'ReportController@index')->middleware('auth');

// Galih Route

Route::get('/homepage', 'HomepageController@index');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $table = 'users';
    protected $fillable = ['name', 'email', 'password'];
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */




    public function index()
    {
        $data['title'] = "Employee";
        $data['menu'] = 3;
        $data['employees'] = Employee::all();
        $data['no'] = 1;
        return view('employee.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['title'] = "Add Data Employee";
        $data['menu'] = 3;
        return view('employee.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'name' => 'required|string|max:150',
            'email' => 'required|string|max:150|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);
        if($validate) {
            $input = [];
            $input['name'] = $request->name;
            $input['email'] = $request->email;
            $input['password'] = bcrypt($request->password);
            $insert = Employee::create($input);
            if($insert) {
                $request->session()->flash('success', 'Add employee success!');
                return redirect()->route('employee.index');
            } else {
                $request->session()->flash('danger', 'Add employee failed!');
                return redirect()->route('employee.index');
            }
        }
        
            
      
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['title'] = "Edit Data Employee";
        $data['menu'] = 3;
        $data['employee'] = Employee::find($id);
        return view('employee.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'name' => 'required|string|max:150',
            
        ]);
        $employee = Employee::find($id);

        if($request->email == $employee->email){
            $update = Employee::find($id)->update([
                'name' =>  $request['name'], 
            ]); 
            $request->session()->flash('success', 'Edit user success!');
            return redirect()->route('employee.index');
        } else {
            $update = Employee::find($id)->update($request->toArray());
            if($update) {
                $request->session()->flash('success', 'Edit user success!');
                return redirect()->route('employee.index');
            } else {
                $request->session()->flash('danger', 'Edit user failed!');
                return redirect()->route('employee.index');
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/employee/create.blade.php
@extends('layouts.app')

@section('content')

<section class="content col-md-6">

    @if ($errors->any())
        
        @foreach ($errors->all() as $error)
            <p class="alert alert-danger">{{ $error }}</p>
        @endforeach
           
    @endif

    <div class="card card-secondary card-outline">
        <div class="card-header">
            <h3 class="card-title">Form {{$title}} </h3>
        </div>
        <div class="card-body">
            <form action="{{ route('employee.store') }}" method="POST">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <p>Name</p>
                            <input type="text" class="form-control" required name="name" value="{{ old('name') }}" >
                        </div>
                        <div class="form-group">
                            <p>Email</p>
                            <input type="email" class="form-control" required name="email" value="{{ old('email') }}">
                        </div>
                        <div class="form-group">
                            <p>Password</p>
                            <input type="password" class="form-control" required name="password" value="{{ old('password') }}">
                        </div>
                        <div class="form-group">
                            <p>Re-type Password</p>
                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                        </div>
                    </div>
            
                </div>
                <input type="submit">
            </form>
        </div>
    </div>
</section> 

@endsection

resources/views/employee/edit.blade.php
@extends('layouts.app')

@section('content')

<section class="content col-md-6">

    @if ($errors->any())
        
        @foreach ($errors->all() as $error)
            <p class="alert alert-danger">{{ $error }}</p>
        @endforeach
           
    @endif

    <div class="card card-secondary card-outline">
        <div class="card-header">
            <h3 class="card-title">Form {{$title}} </h3>
        </div>
        <div class="card-body">
            <form action="{{ route('employee.update', ['id' => $employee->id]) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <p>Name</p>
                            <input type="text" class="form-control" required name="name" value="{{ $employee->name }}" >
                        </div>
                        <div class="form-group">
                            <p>Email</p>
                            <input type="email" class="form-control" required name="email" value="{{ $employee->email }}">
                        </div>
                    </div>
            
                </div>
                <input type="submit">
            </form>
        </div>
    </div>
</section> 

@endsection

resources/views/employee/index.blade.php
@extends('layouts.app')

@section('content')

<section class="content">
    <div class="card card-secondary card-outline">
        <div class="card-header">
            <h3 class="card-title"><a href="{{ route('employee.create') }}" class="btn btn-primary">Add New </a> </h3>
        </div>
        <div class="card-body">
            <table class="table table-sm" id="myTable">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Register Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($employees as $row)
                    @php $create = explode(' ', $row['created_at']);  @endphp

                    <tr>
                        <td>{{ $no++}}</td>
                        <td>{{ $row['name'] }}</td>
                        <td>{{ $row['email'] }}</td>
                        <td>{{ $create[0] }}</td>
                       
                        <td> 
                            <a href="{{ route('employee.edit',  ['id' => $row["id"]]) }}" class="btn btn-sm btn-warning"><i class="fa fa-cog"></i></a>
                            
                        </td>
                    </tr>
                    @endforeach
                </tbody>

            </table>
        </div>
    </div>
</section>                  

@endsection