routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $data['title'] = "Login ";
    return view('auth.login', $data);
})->middleware('guest');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('car', 'CarController')->middleware('auth');

Route::resource('brand', 'BrandController')->middleware('auth');

Route::resource('employee', 'EmployeeController')->middleware('auth');

Route::resource('client', 'ClientController')->middleware('auth');

Route::get('booking', ['as' => 'booking.index', 'uses' => 'BookingController@index' ])->middleware('auth');

Route::get('list-member', 'BookingController@listMember' )->middleware('auth');

Route::post('create-client', ['as' => 'create-client', 'uses' => 'BookingController@createClient' ])->middleware('auth');

Route::post('booking/details', ['as' => 'booking.calculate', 'uses' => 'BookingController@calculate'])->middleware('auth');

Route::post('booking/process', ['as' => 'booking.process', 'uses' => 'BookingController@process'])->middleware('auth');

Route::get('returns', ['as' => 'returns.index', 'uses' => 'ReturnController@index' ])->middleware('auth');

Route::get('returns/information', ['as' => 'returns.information', 'uses' => 'ReturnController@information'])->middleware('auth');

Route::post('returns/process', ['as' => 'returns.process', 'uses' => 'ReturnController@process'])->middleware('auth');

Route::get('reports/transaction', 'ReportController@index')->middleware('auth');

// Galih Route

Route::get('/homepage', 'HomepageController@index');

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Car extends Model
{
    protected $fillable = ['car_name', 'year', 'license_plat', 'price', 'type', 'brand_id', 'available'];
    protected $primaryKey = 'car_id';
    use SoftDeletes;
    protected $dates = ['delete_at'];
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Car;
use App\Brand;
use Illuminate\Support\Facades\DB;

class CarController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['title'] = "Cars";
        $data['menu'] = 1;
        $cars = DB::table('cars')
                        ->join('brands', 'cars.brand_id', '=', 'brands.brand_id')
                        ->get()->toArray();
        //ngereturn array dari query builder laravel
        $data['cars'] = json_decode(json_encode($cars), true);
        //catatan : besok2 pake notasi objek aja kalo nampilin data dari eloqeunt or dari db
        $data['no'] = 1;
        return view('car.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['title'] = "Add New Cars";
        $data['menu'] = 1;
        $data['brands'] = Brand::all();
        
        return view('car.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'car_name' => 'required',
            'year' => 'required|numeric',
            'license_plat' => 'required|max:10',
            'price' => 'required|numeric',
            'type' => 'required',
            'brand_id' => 'required'
        ]);

        $insert = Car::create($request->toArray());

        return redirect()->route('car.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['title'] = "Edit Cars";
        $data['menu'] = 1;
        $data['car'] = Car::find($id);
        $data['brands'] = Brand::all();
        
        return view('car.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'car_name' => 'required',
            'year' => 'required|numeric',
            'license_plat' => 'required|max:10',
            'price' => 'required|numeric',
            'type' => 'required',
            'brand_id' => 'required'
        ]);

        $update = Car::find($id)->update($request->toArray());
        return redirect()->route('car.index');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Car::destroy($id);
        return redirect()->route('car.index');
    }
}

resources/views/car/create.blade.php
@extends('layouts.app')

@section('content')

<section class="content col-md-12">

    @if ($errors->any())
        
        @foreach ($errors->all() as $error)
            <p class="alert alert-danger">{{ $error }}</p>
        @endforeach
           
    @endif

    <div class="card card-secondary card-outline">
        <div class="card-header">
            <h3 class="card-title">Form {{$title}} </h3>
        </div>
        <div class="card-body">
            <form action="{{ route('car.store') }}" method="POST">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <p>Car Name</p>
                            <input type="text" class="form-control" required name="car_name" value="{{ old('car_name') }}" >
                        </div>
                        <div class="form-group">
                            <p>Year</p>
                            <input type="number" class="form-control" required name="year" value="{{ old('year') }}">
                        </div>
                        <div class="form-group">
                            <p>License Plat</p>
                            <input type="text" class="form-control" required name="license_plat" value="{{ old('license_plat') }}">
                        </div>
                    </div>
            
                    <div class="col-md-6">
                        <div class="form-group">
                            <p>Price</p>
                            <input type="number" class="form-control" required name="price" value="{{ old('price') }}">
                        </div>
                        <div class="form-group">
                            <p>Type</p>
                            <select name="type" class="form-control">
                                <option>- Select one -</option>
                                <option value="manual" {{ (old("type") == 'manual' ? "selected":"") }}>Manual</option>
                                <option value="matic" {{ (old("type") == 'matic' ? "selected":"") }}>Matic</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <p>Brand</p>
                            <select name="brand_id" class="form-control">
                                <option value=''>- Select one -</option>
                                @foreach($brands as $list)
                                    <option value="{{ $list['brand_id'] }}"> {{$list['brand_name']}} </option>
                                @endforeach
                            </select>
                            
                        </div>
                    </div>
                </div>
                <input type="submit">
            </form>
        </div>
    </div>
</section> 

@endsection

resources/views/car/edit.blade.php
@extends('layouts.app')

@section('content')

<section class="content col-md-12">
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <p class="alert alert-danger">{{ $error }}</p>
        @endforeach
    @endif

    <div class="card card-secondary card-outline">
        <div class="card-header">
            <h3 class="card-title">Form {{$title}} </h3>
        </div>
        <div class="card-body">
            <form action="{{ route('car.update', ['car_id' => $car->car_id]) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <p>Car Name</p>
                            <input type="text" class="form-control" required name="car_name" value="{{ $car->car_name }}" >
                        </div>
                        <div class="form-group">
                            <p>Year</p>
                            <input type="number" class="form-control" required name="year" value="{{ $car->year }}">
                        </div>
                        <div class="form-group">
                            <p>License Plat</p>
                            <input type="text" class="form-control" required name="license_plat" value="{{ $car->license_plat }}">
                        </div>
                    </div>
            
                    <div class="col-md-6">
                        <div class="form-group">
                            <p>Price</p>
                            <input type="number" class="form-control" required name="price" value="{{ $car->price }}">
                        </div>
                        <div class="form-group">
                            <p>Type</p>
                            <select name="type" class="form-control">
                                <option>- Select one -</option>
                                <option value="manual" {{ ($car->type == 'manual' ? "selected":"") }}>Manual</option>
                                <option value="matic" {{ ($car->type == 'matic' ? "selected":"") }}>Matic</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <p>Brand</p>
                            <select name="brand_id" class="form-control">
                                <option value="">- Select one -</option>
                                @foreach($brands as $brand)
                                    <option value="{{$brand->brand_id}}" {{($car->brand_id == $brand->brand_id ? 'selected' : '')}} >{{$brand->brand_name}}</option>
                                 @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <input type="submit">
            </form>
        </div>
    </div>
</section> 

@endsection

resources/views/car/index.blade.php
@extends('layouts.app')

@section('content')

<section class="content">
    <div class="card card-secondary card-outline">
        <div class="card-header">
            <h3 class="card-title"><a href="{{ route('car.create') }}" class="btn btn-primary">Add New </a> </h3>
        </div>
        <div class="card-body">
            <table class="table table-sm" id="myTable">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Car Name</th>
                        <th>Year</th>
                        <th>License</th>
                        <th>Price</th>
                        <th>Type</th>
                        <th>Brand</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($cars as $row)
                    <tr>
                        <td>{{ $no++}}</td>
                        <td>{{ $row['car_name'] }}</td>
                        <td>{{ $row['year'] }}</td>
                        <td>{{ $row['license_plat'] }}</td>
                        <td>{{ number_format($row['price']) }}</td>
                        <td>{{ $row['type'] }}</td>
                        <td>{{ $row['brand_name'] }}</td>
                        <td> 
                            <a href="{{ route('car.edit',  ['car_id' => $row["car_id"]]) }}" class="btn btn-sm btn-warning"><i class="fa fa-cog"></i></a>
                            <a data-id="{{$row['car_id']}}" class="btn btn-sm btn-danger delete-btn"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>

            </table>
        </div>
    </div>
</section>                  

@endsection

@push('scripts')
<script>
    $(".delete-btn").click(function(){
        let id = $(this).attr('data-id');
        if(confirm("Apa anda yakin akan menghapus? ")) {
            $.ajax({
                url : "{{url('/')}}/car/"+id,
                method : "POST",
                data : {
                    _token : "{{csrf_token()}}",
                    _method : "DELETE",
                }
            })
            .then(function(data){
                location.reload();
            });
        }
    })
</script>
@endpush